version: '2.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  webapp:
    image: mongogrid
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_NAME=test
      - SPRING_PROFILES_ACTIVE=container